### ISSUE TITLE
::OpenURI.open uri'

### ISSUE THREAD

**Issue by cmirnow** [phlegx/money-openexchangerates-bank#1]
I was forced to fix from ['open'](https://github.com/phlegx/money-openexchangerates-bank/blob/master/lib/money/bank/openexchangerates_bank.rb#L269) to '**::OpenURI.open uri**' for this to start working. Otherwise I get 'No such file or directory @ rb_sysopen'.
Perhaps you can fix this problem? Thank you.

P.S. ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux], Rails 6.0.3.4

**Comment by phlegx** [comment]
Resolved via #3
